#Database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/kyn_new
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    jpa: 
        hibernate: 
            ddl-auto: update
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQL8Dialect
    
    security:
        oauth2:
          client:
            registration:
                google:
                  clientId: 260088487728-d3v4r76keah2gt384mrchb0qpqspmdau.apps.googleusercontent.com
                  clientSecret: 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
                  redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                  scope:
                      - email
                      - profile
app:
  auth:
    #tokenSecret: you can use https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx ->Encryption Key Hex enabled  512 bit and 5x
    tokenSecret: 7Q8R9TBUCVEXFYG2J3K4M6P7Q8M5N6Q8R9SBUCVDXFYGZH3K4M5P2J3M5N6P8R9SAUCVDWEYGZH2K4FYH2J3K5N6P7Q9SATBVDWEXGZHVEXFYG2J3K4M6P7Q8SATBUDWEX
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080
  oauth2:
    # redirection uri
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
  
